routes/web.php
<?php

use App\Models\Order;
use App\Models\User;
use App\Models\Customer;
use Illuminate\Http\Request;
use Ipecompany\Smsirlaravel\Smsirlaravel;

Route::get('/', function () {
    dd(1);
    return view('pages.home-page');
});
Route::get('/submit', function () {
    return response()->json(['status'=>'success', 'message'=>'عملیات موفق']);
});

Auth::routes();
Route::get('/locked', 'HomeController@locked')->name('locked');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::post('/unlock', 'HomeController@unlock')->name('unlock');
Route::post('/login_attempt_count', 'Auth\LoginController@attempt_count');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/blog/{filter?}', 'HomeController@blog')->name('blog');
Route::get('/search', 'HomeController@blog_search')->name('blog_search');
Route::post('/blog/store_comment', 'HomeController@store_comment')->name('store_comment');
Route::get('/blog-single/{slug}', 'HomeController@blog_single')->name('blog_single');

Route::delete('/customer/delete','CustomerController@destroy');
Route::put('/customer/update','CustomerController@update');

//Route::post('/receiver/store','ReceiverController@store');
//Route::get('/receiver/delete/{id}','ReceiverController@delete');
//Route::post('/receiver/update/{id}','ReceiverController@update');

//Route::post('/product/store','ProductController@store');
//Route::get('/product/delete/{id}','ProductController@delete');
//Route::post('/product/update/{id}','ProductController@update');

//Route::post('/car/store','CarController@store');
//Route::get('/car/delete/{id}','CarController@delete');
//Route::post('/car/update/{id}','CarController@update');
Route::group(['middleware' => ['isAdmin'],'prefix'=>'admin','namespace'=>'Admin'], function () {
    Route::resource('customer','CustomerController');
    Route::get('customer/manage_address/{id}','CustomerController@manage_address');
    Route::resource('order','OrderController');
    Route::resource('driver','DriverController');
    Route::resource('car','CarController');
    Route::resource('car_type','CarTypeController');
    Route::resource('car_feature','CarFeatureController');
    Route::resource('province','ProvinceController');
    Route::resource('city','CityController');
    Route::resource('price','PriceController');
    Route::get('car_price/{id}','PriceController@car_price');
    Route::get('driver_request/{id}','DriverController@driver_request');
    Route::post('driver_accept','DriverController@driver_accept');
    Route::resource('packing','PackingController');
    Route::resource('product','ProductController');
    Route::get('customer/prepends/get','CustomerController@prepends');
    Route::get('driver/get/details','DriverController@get');
    Route::get('order/all/get','OrderController@get_details');
    Route::get('receiver/get/details','ReceiverController@details');
    Route::get('customer/{id}/address','CustomerController@get_address');
    Route::post('customer/store_data/address','CustomerController@store_data');
    Route::resource('receiver','ReceiverController');
    Route::get('customer/address/{id}','CustomerController@address');
    Route::resource('customer_address','CustomerAddressController');
    Route::get('contact','HomeController@contact_all');
    Route::get('news_letter','HomeController@news_letter');
    Route::get('gift','HomeController@gift');
    Route::PUT('gift/{id}','HomeController@gift_update');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('order','OrderController');
    Route::post('order/get/address','OrderController@get_address')->name('user.get_address');
    Route::post('order/edit/address','OrderController@edit_address')->name('user.edit_address');
    Route::post('order/get/all_address','OrderController@get_all_address_request')->name('get_all_address_request');
    Route::post('order/get/calculate_way_price','OrderController@calculate_way_price')->name('calculate_way_price');

    Route::post('/order', 'OrderController@index')->name('order.index.post');
    Route::post('/order_request/store', 'OrderController@store')->name('order_request.store');
});



//Route::resource('customer','CustomerController');
Route::get('customer/status/{id}','CustomerController@status')->name('custmer_status');
Route::resource('customer_address','CustomerAddressController');

Route::get('/bars/{filters}', 'OrderController@bars')->name('bars')->middleware('isDriver');
Route::get('/bars', 'OrderController@bars')->name('bars')->middleware('isDriver');

Route::resource('car','CarController');
Route::resource('product','ProductController');
Route::resource('car_type','CarTypeController');
Route::resource('driver','DriverController');
Route::resource('customer','CustomerController');
Route::resource('user','UserController');
Route::resource('receiver','ReceiverController');
Route::get('user/trips/old','UserController@old_trips')->name('user.old_trips');
Route::get('user/trips/request','UserController@request_trips')->name('user.request_trips');
Route::get('user/bars/request','UserController@request_bars')->name('user.request_bars');
Route::get('user/bars/finished','UserController@finished_bars')->name('user.finished_bars');
Route::get('user/bars/in_way','UserController@in_way_bars')->name('user.in_way_bars');
Route::get('user/manage/address','UserController@manage_address')->name('user.manage_address');
Route::get('user/manage/password','UserController@change_password')->name('user.change_password');
Route::post('user/update/password','UserController@update_password')->name('user.update_password');
Route::post('user/update/profile','UserController@update_profile')->name('user.update_profile');

Route::get('/','HomeController@index');
Route::get('/login/{type}','Auth\LoginController@login_type');
Route::post('/login_attempt','Auth\LoginController@login_attempt');
Route::get('/confirm','Auth\LoginController@confirm_view');
Route::post('/confirm','Auth\LoginController@confirm_validate');
Route::get('/forgot_password','Auth\LoginController@forgot_password_view');
Route::post('/forgot_password','Auth\LoginController@forgot_password');
//Route::get('/login/{type}','HomeController@login');
//Route::post('/login','HomeController@login_attemp');
//Route::get('/confirm','HomeController@confirm_view');
//Route::post('/confirm','HomeController@confirm');
//Route::get('/forgot_password','HomeController@forgot_password_view');
//Route::post('/forgot_password','HomeController@forgot_password');

Route::get('/get_cities','HomeController@get_cities');
Route::get('/check_phone','HomeController@check_phone');
Route::post('/get_ten_last_request','OrderController@get_ten_last_request')->name('get_ten_last_request');
Route::get('/inquiry','OrderController@inquiry');
Route::post('/get_orders','OrderController@get_orders');
Route::post('driver_accept','OrderController@driver_accept');
Route::post('contact','homeController@contact_submit')->name('contact');
Route::post('news_letter','homeController@news_letter_store')->name('contact');
Route::get('/test',function (){
    dd(auth()->user());
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;
class User extends Authenticatable
{
    use Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name','last_name', 'role_id','photo_id','object_id','email','mobile', 'password','active', 'email_verified_at','remember_token','code'];
    protected $appends=['name'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

//    public function getJWTIdentifier()
//    {
//        return $this->getKey();
//    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
//    public function getJWTCustomClaims()
//    {
//        return [];
//    }

    public function sendPasswordResetNotification($token)
    {
        // Your your own implementation.
        $this->notify(new ResetPasswordNotification($token));
    }

/*    public function getFirstNameAttribute(){
        $name=explode(' ',$this->name);
        return $name[0];
    }*/

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }

    public function getImageAttribute()
    {
        return isset($this->photo->path) ? asset($this->photo->path) : asset('site/images/blog/avatar-1.png');
    }

    public function object()
    {
//        if($this->role->slug=='customer')
//            return $this->hasOne(Customer::class);
//        if($this->role->slug=='driver')
//            return $this->hasOne(Driver::class);
    if(auth()->user())
        if(in_array(auth()->user()->role_id,[1,2]))
        {
            $class=auth()->user()->role_id==1?Driver::class:Customer::class;
            return $class::find($this->object_id);
        }

     dd('You Are Admin');
    }

    public function getFullNameAttribute()
    {
        if($this->first_name==null && $this->last_name==null )
            return 'کاربر گرامی';
        $prepends=get_prepends();
        $prepend='';
        if($this->object()->prepend!=null)
            $prepend=$prepends[$this->object()->prepend];
        return $prepend.' '.$this->first_name.' '.$this->last_name;
    }

    public function getNameAttribute()
    {
        return $this->first_name.' '.$this->last_name;
    }


}

resources/views/site/parts/cooperation.blade.php
<section class="all-sections driver-page-cooperation">
    <div class="top-section container">
        <h2 class="title mb-4">
            نحوه همکاری بارلند با رانندگان
        </h2>
        <p class="description text-justify">
            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
            چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای
            متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و
            متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان
            فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد
            وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
        </p>
    </div>
</section>

resources/views/site/parts/customer-main-board.blade.php
<section class="main-board customer">
    <div class="box-inputs">
        <form id="get_price_and_order_registration_form">
            <div class="form-group">
                <label for="form_order_from">مبدا را انتخاب کنید</label>
                <select name="form_order_from" id="form_order_from" class="form-control select2">
                    <option value=""></option>
                    @foreach(\App\Models\Province::where('accepted',1)->get() as $province)
                        @foreach($province->cities()->where('accepted',1)->get() as $city)
                            <option value="{{$city->id}}" >{{$city->title}} ({{$province->title}})</option>
                        @endforeach
                    @endforeach
                </select>
                <!--<small id="formHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
            </div>
            <div class="form-group">
                <label for="form_order_to">مقصد را انتخاب کنید</label>
                <select name="form_order_to" id="form_order_to" class="form-control select2">
                    <option value=""></option>
                    @foreach(\App\Models\City::all()  as $city)
                        <option value="{{$city->id}}" >{{$city->title}} ({{$city->province->title}})</option>
                    @endforeach
                </select>
                <!--<small id="toHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
            </div>

            <hr>

            <div class="form-group">
                <label>نوع خودرو را انتخاب کنید</label>
                <div class="box-inputs-toggle">
                    @foreach($car_types as $car_type)
                        {{--<input type="radio" onchange="get_car_feature(this);" {{$loop->index==0?'checked':''}} name="form_order_car_type" value="{{$car_type->id}}" id="car_type_{{$car_type->id}}" />--}}
                        <input type="radio" {{$loop->index==0?'checked':''}} name="form_order_car_type" value="{{$car_type->id}}" id="car_type_{{$car_type->id}}" />
                        <label for="car_type_{{$car_type->id}}">{{$car_type->title}}</label>
                    @endforeach

                </div>
            </div>

            <hr>

            <div class="register-new text-center">
                <a href="javascript:;" class="btn" onclick="get_price_and_order_registration();">
                    <span> استعلام قیمت و ثبت سفارش</span>
                    <i class="fas fa-long-arrow-alt-left"></i>
                </a>
            </div>
        </form>


        <div id="customer_order_registration" class="mz-hidden">
            <div class="text-center order_registration">
                <p>میانگین قیمت 5 سفر آخر در این مسیر</p>
                <h2><strong id="average_request">1,000</strong> تومان </h2>
            </div>
            <hr>
            <div class="text-center order_registration">
                <p>تعرفه باربری برای مسیر درخواستی شما</p>
                <h2><strong id="tariff_request">500</strong> تومان </h2>
            </div>
            <hr>
            <div class="register-newf text-center">
                <a href="javascript:;" class="btn" onclick="go_to_order_page_form();">
                    <span> ثبت سفارش</span>
                    <i class="fas fa-long-arrow-alt-left"></i>
                </a>
                <form action="{{Route('order.index.post')}}" method="post" id="go_to_order_page_form"></form>
            </div>
        </div>
    </div>
</section>

resources/views/site/parts/download-app.blade.php
<section class="all-sections driver-page-download-app">
    <div class="section-content">
        <div class="row">
            <div class="col-4 right-box">
                <div class="img"><img src="{{asset('site/images/download-app.png')}}" alt="download-app"/></div>
            </div>
            <div class="col-8 left-box text-center">
                <h3>در این بخش میتوانید اپلیکیشن بارلند را دانلود کنید</h3>
                <div class="images">

                    <img src="{{asset('site/images/app-google-play.png')}}" alt="work-car" />
                    <img src="{{asset('site/images/app-bazar.png')}}" alt="work-car" />
                </div>
                <div class="download-box">
                    <input type="text" placeholder="شماره تلفن خود را وارد کنید">
                    <a href="#">دریافت اپلیکیشن</a>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/site/parts/driver-main-board.blade.php
<section class="main-board driver">
    <div class="box-inputs">
        @auth
            <form action="">
                <div class="form-group">
                    <label for="filter_from_state">استان مبدا</label>
                    <select class="form-control select2" name="filter_from_state" id="filter_from_state" onchange="change_cities(this,'from');">
                        <option value=""></option>
                        @foreach(\App\Models\Province::get_accepted_provinces() as $province)
                            <option value="{{$province->id}}">{{$province->title}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="filter_from_city">شهر مبدا</label>
                    <select class="form-control select2" name="filter_from_city" id="filter_from_city">
                        <option value=""></option>
                    </select>
                </div>
                <hr>
                <div class="form-group">
                    <label for="filter_to_state">استان مقصد</label>
                    <select class="form-control select2" name="filter_to_state" id="filter_to_state" onchange="change_cities(this,'to');">
                        <option value=""></option>
                        @foreach(\App\Models\Province::get_provinces()->get() as $province)
                            <option value="{{$province->id}}">{{$province->title}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="filter_to_city">شهر مقصد</label>
                    <select class="form-control select2" name="filter_to_city" id="filter_to_city">
                        <option value=""></option>
                    </select>
                </div>

                <div class="register-new text-center">
                    <a href="javascript:;" onclick="get_bars();" class="btn">جستجوی بار</a>
                </div>
            </form>
        @endauth
        @guest
            <form action="{{asset('driver')}}" method="post" id="driver_form_id">
                <div class="form-group">
                    <label for="first_name">نام</label>
                    <input type="text" class="form-control" id="first_name" aria-describedby="formHelp" name="first_name">
                </div>
                <div class="form-group">
                    <label for="last_name">نام خانوادگی</label>
                    <input type="text" class="form-control" id="last_name" name="last_name">
                </div>
                <div class="form-group">
                    <label for="mobile">شماره همراه</label>
                    <input type="text" class="form-control" id="mobile" name="mobile">
                </div>

                <hr>

                <div class="form-group">
                    <label>نوع خودروی خود را انتخاب کنید</label>
                    <div class="box-inputs-toggle">
                        @foreach($car_types as $car_type)
                            <input type="radio" {{$loop->index==0?'checked':''}} onchange="get_car_feature(this);" name="car_type" value="{{$car_type->id}}" id="car_type_{{$car_type->id}}" />
                            <label for="car_type_{{$car_type->id}}">{{$car_type->title}}</label>
                        @endforeach
                    </div>
                </div>

                <div class="form-group">
                    <label for="car_feature">ویژگی خودروی خود را انتخاب کنید</label>
                    <select class="form-control" id="car_feature" name="car_feature_id">
                        <option value=""></option>
                        @foreach($car_features as $type)
                            @if($type['car_type_id']==$car_types[0]['id'])
                                <option value="{{$type->id}}">{{$type->title}}</option>
                            @endif
                        @endforeach
                    </select>
                </div>

                <hr>
                <div class="form-group form-check">
                    <label class="form-check-label" for="accept-rules">
                        <input type="checkbox" class="form-check-input" id="accept-rules" name="accept_rules">
                        <a href="#" class="accept-rules">شرایط و قوانین </a>سایت را میپذیرم
                    </label>

                </div>

                <div class="register-new text-center">
                    <a href="javascript:;" onclick="store_new_driver();" class="btn">ثبت نام</a>
                </div>
            </form>
        @endguest
    </div>
</section>

resources/views/site/parts/footer.blade.php
<section class="all-sections driver-page-footer">
    <footer>
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 all-columns first-child">
                <div class="item-head">
                    <h3>دسترسی سریع</h3>
                </div>
                <div class="item-content">
                    <ul>
                        <li><a href="#">سوالات متداول</a></li>
                        <li><a href="#">تماس با ما</a></li>
                        <li><a href="#">خبرنامه</a></li>
                        <li><a href="#">درباره ما</a></li>
                        <li><a href="#">فرصت های شغلی</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 all-columns contract">
                <div class="item-head">
                    <h3>اطلاعات تماس</h3>
                </div>
                <div class="item-content">
                    <ul>
                        <li>
                            <span>آدرس:</span>
                            <span class="text">استان تهران، خیابان ستارخان، خیابان پاتریس، کوچه سیامکی، خیابان ستارخان، خیابان پاتریس، کوچه سیامکی، پلاک 57</span>
                        </li>
                        <li>
                            <span>شماره تلفن:</span>
                            <a href="tel:09353322681">09353322681</a>
                        </li>
                        <li>
                            <span>ایمیل:</span>
                            <a href="mailto:support@barland.ir">support@barland.ir</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 all-columns newsletter">
                <div class="item-head">
                    <h3>عضویت در خبرنامه</h3>
                </div>
                <div class="item-content">
                    <form action="" id="news_letter" >
                        <input type="text" name="email" class="form-control" placeholder="ایمیل خود را وارد کنید">
                        <a href="javascript:;" onclick="submit(this);">ثبت</a>
                    </form>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-12 all-columns">
                <img src="{{asset('site/images/e-nemad.png')}}" alt="نماد الکترونیک" />
            </div>
        </div>
    </footer>
</section>

<section class="driver-page-copy-right">
    <div class="container">
        <p>تمام حقوق مادی و معنوی سایت مربوط به بارلند میباشد</p>
    </div>
</section>

<script>
    function submit() {
        let form_id = '#news_letter';
        if (!validation(form_id))
            return;
        swal.fire({
            title: 'لطفا منتظر بمانید',
            text:'درحال ثبت اطلاعات',
            allowOutsideClick:false,
            onOpen: function() {
                swal.showLoading()
            }
        });
        let form=$(form_id);

        let formData=new FormData(form[0]);
        let url ="{{asset('news_letter')}}";
        $.ajax(url, {
            data: formData,
            type: 'post',
            dataType: 'json',
            headers: {'X-CSRF-TOKEN': "{{csrf_token()}}",},
            contentType: false,
            cache: false,
            processData: false,
            success: function (response) {
                swal.close();
                if(response.status==='success') {
                    swal.fire({
                        title: 'عملیات موفق',
                        text: response.message,
                        type: "success",
                        confirmButtonText: 'بسیار خب',
                        confirmButtonClass: "btn btn-brand"
                    });
                    form.find('.form-control').val('');
                }
                if(response.status==='error') {
                    swal.fire({
                        title: 'عملیات ناموفق',
                        text: response.message,
                        type: "error",
                        confirmButtonText: 'بسیار خب',
                        confirmButtonClass: "btn btn-brand"
                    });
                }
            },
            error: function (data) {
                swal.close();
                let status = 'error';
                let myTitle = 'عملیات ناموفق';
                let message = 'عملیات بامشکل مواجه شد. لطفا با پشتیبانی تماس حاصل فرمایید.';
                ToastrMessage(myTitle, message, status);
            }
        });


    }
    function validation(element) {
        let form=$(element);
        let all_rules={rules:{
                email:{
                    required:true,
                    email: true
                },
            }
        };

        form.validate(all_rules);
        if(!form.valid())
            return false;
        return true;
    }




</script>

resources/views/site/parts/footer_nav.blade.php
<div id="sidebar-nav-toggle" class="sidebar-nav-toggle">
    <div class="top-close-button">
        <a href="javascript:void(0)" onclick="closeNav()"><i class="fas fa-times"></i></a>
    </div>

    <ul class="menu-items">
        <li><a href="{{asset('/')}}" onclick="closeNav()">صفحه اصلی</a></li>
        <li><a href="{{asset('/login')}}">ورود/عضویت</a></li>
        <li><a href="{{asset('/about')}}" onclick="closeNav()">درباره ما</a></li>
        <li><a href="{{asset('/faq')}}" onclick="closeNav()">سوالات متداول</a></li>
        @if(get_role()=='customer')
            <li><a href="{{asset('/order')}}">درخواست بار جدید</a></li>
        @endif
        <li><a href="{{asset('/contact')}}" onclick="closeNav()">تماس با ما</a></li>
        <li><a href="{{asset('/news-latter')}}" onclick="closeNav()">خبرنامه</a></li>
        @if(get_role()=='customer')
            <li><a href="{{asset('/partners')}}" onclick="closeNav()">همکاران ما</a></li>
        @endif
    </ul>

    <div class="socials">
        <ul class="social-items">
            <li><a href="#" onclick="closeNav()"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#" onclick="closeNav()"><i class="fab fa-instagram"></i></a></li>
            <li><a href="#" onclick="closeNav()"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
    </div>
</div>

<div id="nav-overlay" onclick="closeNav()">
    <div class="close-button">
        <a href="javascript:void(0)" onclick="closeNav()">بستن</a>
    </div>
</div>

resources/views/site/parts/menu.blade.php
<nav class="top-navigation {{top_navigation_class()}}">
    <ul class="menu hidden-xs">
        @auth
            <li><a href="javascript:;" onclick="dropdown_menu_item(this);">{{auth()->user()->full_name}} <i class="fas fa-chevron-left has-sub-menu"></i></a>
                <ul>
                    <li><a href="{{route('user.index')}}"><i class="fas fa-home"></i> پروفایل </a></li>
                    <li><a href="javascript:;" onclick="document.getElementById('logout_user_form').submit();"><i class="fas fa-sign-out-alt"></i> خروج </a>
                        <form action="{{route('logout')}}" method="post" id="logout_user_form">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        @endauth
        @guest
            <li><a href="{{asset('/login/'.get_type_of_login())}}">{{get_type_of_login()=='driver'?'ورود':'ورود/عضویت'}}</a></li>
        @endguest
        <li><a href="{{asset('/')}}">صفحه اصلی</a></li>
        @if(get_role()=='driver')
            <li class="{{request()->path()=='bars'?'active':''}}"><a href="{{asset('/bars')}}"> بار ها</a></li>
        @endif
        @if(get_role()=='customer')
            <li class="{{request()->path()=='order'?'active':''}}"><a href="{{asset('/order')}}">درخواست بار جدید</a></li>
        @endif
        <li class="{{request()->path()=='about'?'active':''}}"><a href="{{asset('/about')}}">درباره ما</a></li>
        <li class="{{request()->path()=='faq'?'active':''}}"><a href="{{asset('/faq')}}">سوالات متداول</a></li>
        {{--@dd($page_type)--}}
        <li class="{{request()->path()=='contact'?'active':''}}"><a href="{{asset('/contact')}}">تماس با ما</a></li>
        <li class="{{request()->path()=='blog'?'active':''}}"><a href="{{asset('/blog')}}">وبلاگ</a></li>
    </ul>
    <div class="logo pull-left">
        <a href="{{asset('/')}}"><img src="{{asset('site/images/logo-white.png')}}" alt="logo" id="site-main-logo"></a>
    </div>

    <nav class="top-right menu navbar-light block-xs">
        <button class="navbar-toggler" type="button" onclick="openNav();">
            <span class="navbar-toggler-icon"></span>
            <span class="title">منو</span>
        </button>
    </nav>
</nav>

resources/views/site/parts/social.blade.php
<section class="driver-page-social">
    <div class="container">
        <div class="pull-right">
            <h6> مارا در شبکه های اجتماعی دنبال کنید</h6>
        </div>
        <div class="pull-left">
            <ul class="social-items">
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
        </div>
    </div>
</section>